### ISSUE TITLE
Roadmap - v0.1.0 

### ISSUE THREAD

**Issue by mykulyak** [mykulyak/astro-slides#1]
### This lists features I'd like to have in v0.1.0.

- [x] presentation and slide structure
- [x] common slide layouts
    - [x] "headings" - title, section, transition
    - [x] about me
    - [x] two columns (1/3 and 2/3 widths), left and right variations
    - [x] two columns (1/2, 1/2) width
    - [x] three columns
- [x] common elements
    - [x] images
    - [x] image stacks
    - [x] placeholders (text, image)
    - [x] links
    - [x] paragraphs
    - [x] emoji
    - [x] code
    - [x] navigation control
    - [x] page number
    - [x] lists and list items
    - [x] photos / avatars
- [x] navigation
    - [x] slides can override slide number control
    - [x] slides can override navigation controls
- [ ] documentation
- [ ] project chores (CoC, contribution guidelines, etc.)
- [ ] theme configuration plugs in into Tailwind config
- [ ] presentation templates
    - [x] default
    - [x] business
    - [ ] fancy (for children)
    - [ ] coding
- [ ] demo presentations
    - [x] default
    - [ ] business
    - [ ] fancy
    - [ ] code heavy (islands, etc.)

**Comment by muhajirdev** [comment]
is this project dead?

**Comment by mykulyak** [comment]
> is this project dead?

Hey, no. I did slow down though (too many changes this year).
